# Generated by Django 5.0.3 on 2024-06-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0008_activitygroup_created_at_activitygroup_updated_at'),
        ('profiles', '0002_rename_profile_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_habit', 'new_habit'), ('new_easier_activity', 'new_easier_activity'), ('new_harder_activity', 'new_harder_activity'), ('new_best_streak', 'new_best_streak'), ('new_more_performed', 'new_more_performed')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
