# Generated by Django 5.0.3 on 2024-03-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_profile_reportactivity_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportactivity',
            name='profile',
        ),
    ]
