# Generated by Django 5.0.3 on 2024-03-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_reportactivity_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactivity',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
